import{S as y,i as l}from"./assets/vendor-BrddEoy-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&o(f)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const b="46234405-5fabb3e7cd0fd4a5073c0abd3",w="https://pixabay.com/api/",g=async(r,t=1,a=12)=>{const o=`${w}?key=${b}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&page=${t}&per_page=${a}`;try{const e=await fetch(o);if(!e.ok)throw new Error(`HTTP error! status: ${e.status}`);return(await e.json()).hits}catch(e){throw console.error("Error fetching images",e),e}};let m;function p(r){const t=document.querySelector(".gallery"),a=r.map(o=>`
    <a href="${o.largeImageURL}" class="gallery-item">
      <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy"/>
      <div class="info">
        <p>Likes: ${o.likes}</p>
        <p>Views: ${o.views}</p>
        <p>Comments: ${o.comments}</p>
        <p>Downloads: ${o.downloads}</p>
      </div>
    </a>
  `).join("");t.insertAdjacentHTML("beforeend",a),m?m.refresh():m=new y(".gallery a")}function $(){document.querySelector(".gallery").innerHTML=""}function h(){document.getElementById("loader").classList.remove("hidden")}function c(){document.getElementById("loader").classList.add("hidden")}const E=document.querySelector("#search-form"),n=document.querySelector("#load-more-btn");let i="",d=1;const u=12;let L=new y(".gallery a");E.addEventListener("submit",async r=>{if(r.preventDefault(),i=r.target.elements.query.value.trim(),!i){l.error({title:"Error",message:"Please enter a search query"}),r.target.elements.query.focus();return}$(),d=1,n.style.display="none";try{h();const t=await g(i,d,u);c(),t.length===0?l.info({title:"Info",message:"Sorry, no images found for your search query."}):(p(t),L.refresh(),t.length===u&&(n.style.display="block"))}catch{c(),l.error({title:"Error",message:"Failed to fetch images. Please try again later."})}});n.addEventListener("click",async()=>{d+=1;try{h();const r=await g(i,d,u);c(),p(r),L.refresh(),r.length<u?n.style.display="none":n.style.display="block"}catch{c(),l.error({title:"Error",message:"Failed to load more images. Please try again later."})}});
//# sourceMappingURL=index.js.map
